-- =============================================
-- 归档与借阅管理表
-- =============================================

CREATE TABLE IF NOT EXISTS `doc_archive` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `doc_id` BIGINT NOT NULL COMMENT '公文ID',
    `archive_no` VARCHAR(64) NOT NULL COMMENT '归档编号',
    `archive_year` INT NOT NULL COMMENT '归档年度',
    `archive_type` VARCHAR(32) COMMENT '文种分类',
    `archive_dept_id` VARCHAR(64) COMMENT '归档部门ID',
    `archive_dept_name` VARCHAR(128) COMMENT '归档部门名称',
    `security_level` VARCHAR(32) COMMENT '密级',
    `archive_method` VARCHAR(16) NOT NULL DEFAULT 'manual' COMMENT '归档方式：manual手动/auto自动',
    `archive_location` VARCHAR(256) COMMENT '存放位置',
    `retention_period` VARCHAR(32) COMMENT '保管期限：permanent永久/long长期(30年)/short短期(10年)',
    `archive_date` DATE NOT NULL COMMENT '归档日期',
    `is_locked` TINYINT NOT NULL DEFAULT 1 COMMENT '是否锁定：0否1是',
    `status` VARCHAR(32) NOT NULL DEFAULT 'archived' COMMENT '状态：archived已归档/transferred已移交/destroyed已销毁',
    `doc_title` VARCHAR(256) COMMENT '公文标题',
    `doc_number` VARCHAR(128) COMMENT '发文字号',
    `doc_type` VARCHAR(32) COMMENT '公文类型',
    `doc_content_snapshot` LONGTEXT COMMENT '公文正文快照',
    `unit_code` VARCHAR(64) COMMENT '所属单位编码',
    `unit_name` VARCHAR(128) COMMENT '所属单位名称',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_archive_no` (`archive_no`),
    KEY `idx_doc_id` (`doc_id`),
    KEY `idx_archive_year` (`archive_year`),
    KEY `idx_archive_type` (`archive_type`),
    KEY `idx_archive_dept_id` (`archive_dept_id`),
    KEY `idx_security_level` (`security_level`),
    KEY `idx_status` (`status`),
    KEY `idx_archive_date` (`archive_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公文归档表';

CREATE TABLE IF NOT EXISTS `doc_borrow` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `archive_id` BIGINT NOT NULL COMMENT '归档记录ID',
    `doc_id` BIGINT NOT NULL COMMENT '公文ID',
    `borrow_no` VARCHAR(64) NOT NULL COMMENT '借阅单号',
    `applicant_id` VARCHAR(64) NOT NULL COMMENT '申请人ID',
    `applicant_name` VARCHAR(64) NOT NULL COMMENT '申请人姓名',
    `applicant_dept_id` VARCHAR(64) COMMENT '申请人部门ID',
    `applicant_dept_name` VARCHAR(128) COMMENT '申请人部门名称',
    `borrow_reason` VARCHAR(512) NOT NULL COMMENT '借阅事由',
    `borrow_type` VARCHAR(16) NOT NULL DEFAULT 'online' COMMENT '借阅方式：online在线/physical实体',
    `start_date` DATE NOT NULL COMMENT '借阅开始日期',
    `end_date` DATE NOT NULL COMMENT '借阅结束日期',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending待审批/approved已批准/rejected已驳回/active借阅中/returned已归还/overdue已逾期',
    `approver_id` VARCHAR(64) COMMENT '审批人ID',
    `approver_name` VARCHAR(64) COMMENT '审批人姓名',
    `approve_time` DATETIME COMMENT '审批时间',
    `approve_opinion` VARCHAR(512) COMMENT '审批意见',
    `return_time` DATETIME COMMENT '归还时间',
    `watermark_text` VARCHAR(256) COMMENT '水印文字',
    `view_count` INT NOT NULL DEFAULT 0 COMMENT '在线查看次数',
    `last_view_time` DATETIME COMMENT '最后查看时间',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_borrow_no` (`borrow_no`),
    KEY `idx_archive_id` (`archive_id`),
    KEY `idx_doc_id` (`doc_id`),
    KEY `idx_applicant_id` (`applicant_id`),
    KEY `idx_status` (`status`),
    KEY `idx_start_date` (`start_date`),
    KEY `idx_end_date` (`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公文借阅表';
