-- =============================================
-- 收文与签收表
-- =============================================

CREATE TABLE IF NOT EXISTS `doc_incoming` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `incoming_no` VARCHAR(64) NOT NULL COMMENT '收文编号',
    `source` VARCHAR(16) NOT NULL DEFAULT 'manual' COMMENT '来源：manual手动录入/api接口接入',
    `source_unit` VARCHAR(256) COMMENT '来文单位',
    `source_doc_number` VARCHAR(128) COMMENT '来文字号',
    `doc_title` VARCHAR(256) NOT NULL COMMENT '公文标题',
    `doc_type` VARCHAR(32) COMMENT '公文类型',
    `security_level` VARCHAR(32) COMMENT '密级',
    `urgency_level` VARCHAR(32) COMMENT '紧急程度',
    `received_date` DATE NOT NULL COMMENT '收文日期',
    `received_method` VARCHAR(32) COMMENT '收文方式：mail邮件/courier专递/fax传真/email电子/in_person当面',
    `copies` INT NOT NULL DEFAULT 1 COMMENT '份数',
    `pages` INT COMMENT '页数',
    `doc_content` LONGTEXT COMMENT '公文正文',
    `attachment_info` VARCHAR(1024) COMMENT '附件信息',
    `keyword` VARCHAR(256) COMMENT '主题词',
    `abstract_text` VARCHAR(1024) COMMENT '摘要',
    `status` VARCHAR(32) NOT NULL DEFAULT 'registered' COMMENT '状态：registered已登记/proposed已拟办/handling承办中/completed已办结/transferred已转发',
    `registrant_id` VARCHAR(64) COMMENT '登记人ID',
    `registrant_name` VARCHAR(64) COMMENT '登记人姓名',
    `registrant_dept_id` VARCHAR(64) COMMENT '登记部门ID',
    `registrant_dept_name` VARCHAR(128) COMMENT '登记部门名称',
    `unit_code` VARCHAR(64) COMMENT '所属单位编码',
    `unit_name` VARCHAR(128) COMMENT '所属单位名称',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_incoming_no` (`incoming_no`),
    KEY `idx_source` (`source`),
    KEY `idx_source_unit` (`source_unit`(64)),
    KEY `idx_received_date` (`received_date`),
    KEY `idx_status` (`status`),
    KEY `idx_doc_type` (`doc_type`),
    KEY `idx_security_level` (`security_level`),
    KEY `idx_registrant_id` (`registrant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收文登记表';

CREATE TABLE IF NOT EXISTS `doc_handling` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `incoming_id` BIGINT NOT NULL COMMENT '收文ID',
    `handling_no` VARCHAR(64) NOT NULL COMMENT '处理编号',
    `handling_type` VARCHAR(32) NOT NULL COMMENT '处理类型：draft_opinion拟办/assign承办/feedback反馈',
    `opinion` VARCHAR(1024) COMMENT '处理意见',
    `handler_id` VARCHAR(64) NOT NULL COMMENT '处理人ID',
    `handler_name` VARCHAR(64) NOT NULL COMMENT '处理人姓名',
    `handler_dept_id` VARCHAR(64) COMMENT '处理人部门ID',
    `handler_dept_name` VARCHAR(128) COMMENT '处理人部门名称',
    `target_dept_id` VARCHAR(64) COMMENT '目标部门ID（拟办转承办时）',
    `target_dept_name` VARCHAR(128) COMMENT '目标部门名称',
    `target_user_id` VARCHAR(64) COMMENT '目标人员ID',
    `target_user_name` VARCHAR(64) COMMENT '目标人员姓名',
    `deadline` DATE COMMENT '办理期限',
    `handling_time` DATETIME COMMENT '处理时间',
    `feedback_content` VARCHAR(1024) COMMENT '反馈内容',
    `feedback_time` DATETIME COMMENT '反馈时间',
    `feedback_attachment` VARCHAR(512) COMMENT '反馈附件',
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending待处理/processing处理中/completed已完成',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_handling_no` (`handling_no`),
    KEY `idx_incoming_id` (`incoming_id`),
    KEY `idx_handling_type` (`handling_type`),
    KEY `idx_handler_id` (`handler_id`),
    KEY `idx_handler_dept_id` (`handler_dept_id`),
    KEY `idx_target_dept_id` (`target_dept_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收文处理表';
