-- =============================================
-- 权限与安全表
-- =============================================

CREATE TABLE IF NOT EXISTS `doc_permission` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `permission_code` VARCHAR(64) NOT NULL COMMENT '权限编码',
    `permission_name` VARCHAR(128) NOT NULL COMMENT '权限名称',
    `permission_type` VARCHAR(32) NOT NULL COMMENT '权限类型：action操作/data数据',
    `security_level` VARCHAR(32) COMMENT '密级限制：普通/秘密/机密/绝密，空表示不限制',
    `allowed_roles` VARCHAR(512) COMMENT '允许的角色ID列表，逗号分隔',
    `allowed_users` VARCHAR(512) COMMENT '允许的用户ID列表，逗号分隔',
    `allowed_depts` VARCHAR(512) COMMENT '允许的部门ID列表，逗号分隔',
    `description` VARCHAR(256) COMMENT '描述',
    `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0否1是',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_permission_code` (`permission_code`),
    KEY `idx_permission_type` (`permission_type`),
    KEY `idx_security_level` (`security_level`),
    KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作权限表';

CREATE TABLE IF NOT EXISTS `doc_audit_log` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `log_no` VARCHAR(64) NOT NULL COMMENT '日志编号',
    `user_id` VARCHAR(64) NOT NULL COMMENT '操作人ID',
    `user_name` VARCHAR(64) NOT NULL COMMENT '操作人姓名',
    `dept_id` VARCHAR(64) COMMENT '操作人部门ID',
    `dept_name` VARCHAR(128) COMMENT '操作人部门名称',
    `action` VARCHAR(64) NOT NULL COMMENT '操作类型：draft/modify/delete/sign/approve/view/archive/export/print',
    `action_name` VARCHAR(128) COMMENT '操作名称',
    `resource_type` VARCHAR(64) COMMENT '资源类型：document/template/seal/signature/workflow/archive/borrow/incoming/handling',
    `resource_id` VARCHAR(128) COMMENT '资源ID',
    `resource_name` VARCHAR(256) COMMENT '资源名称',
    `security_level` VARCHAR(32) COMMENT '公文密级',
    `description` VARCHAR(1024) COMMENT '操作描述',
    `old_value` VARCHAR(1024) COMMENT '变更前值',
    `new_value` VARCHAR(1024) COMMENT '变更后值',
    `ip_address` VARCHAR(64) COMMENT 'IP地址',
    `user_agent` VARCHAR(256) COMMENT '客户端信息',
    `request_url` VARCHAR(512) COMMENT '请求URL',
    `request_method` VARCHAR(16) COMMENT '请求方法',
    `cost_time` BIGINT COMMENT '耗时(ms)',
    `result` VARCHAR(32) NOT NULL DEFAULT 'success' COMMENT '操作结果：success/failure',
    `error_message` VARCHAR(512) COMMENT '错误信息',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    KEY `idx_log_no` (`log_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_action` (`action`),
    KEY `idx_resource_type` (`resource_type`),
    KEY `idx_resource_id` (`resource_id`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_security_level` (`security_level`),
    KEY `idx_result` (`result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作审计日志表';

CREATE TABLE IF NOT EXISTS `doc_integrity` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `doc_id` BIGINT NOT NULL COMMENT '公文ID',
    `content_hash` VARCHAR(128) NOT NULL COMMENT '正文SHA-256哈希',
    `signature_hash` VARCHAR(128) COMMENT '签章数据哈希',
    `hash_algorithm` VARCHAR(32) NOT NULL DEFAULT 'SHA-256' COMMENT '哈希算法',
    `version` INT NOT NULL DEFAULT 1 COMMENT '版本号',
    `verify_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '验证状态：pending待验证/verified已验证/tampered已篡改',
    `verify_time` DATETIME COMMENT '验证时间',
    `verified_by` VARCHAR(64) COMMENT '验证人ID',
    `verified_by_name` VARCHAR(64) COMMENT '验证人姓名',
    `content_snapshot` LONGTEXT COMMENT '正文快照',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    KEY `idx_doc_id` (`doc_id`),
    KEY `idx_content_hash` (`content_hash`),
    KEY `idx_verify_status` (`verify_status`),
    KEY `idx_version` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公文完整性存证表';

INSERT IGNORE INTO `doc_permission` (`id`, `permission_code`, `permission_name`, `permission_type`, `security_level`, `description`, `enabled`, `sort_order`) VALUES
(1, 'doc:draft', '拟稿', 'action', NULL, '创建新公文', 1, 1),
(2, 'doc:modify', '修改', 'action', NULL, '修改公文内容', 1, 2),
(3, 'doc:delete', '删除', 'action', NULL, '删除公文', 1, 3),
(4, 'doc:sign', '签章', 'action', NULL, '对公文进行签章', 1, 4),
(5, 'doc:approve', '审批', 'action', NULL, '审批公文流程', 1, 5),
(6, 'doc:view', '查看', 'action', NULL, '查看公文内容', 1, 6),
(7, 'doc:archive', '归档', 'action', NULL, '归档公文', 1, 7),
(8, 'doc:view:secret', '查看秘密公文', 'data', '秘密', '查看秘密级及以上公文', 1, 10),
(9, 'doc:view:confidential', '查看机密公文', 'data', '机密', '查看机密级及以上公文', 1, 11),
(10, 'doc:view:top_secret', '查看绝密公文', 'data', '绝密', '查看绝密级公文', 1, 12),
(11, 'doc:export', '导出', 'action', NULL, '导出公文', 1, 8),
(12, 'doc:print', '打印', 'action', NULL, '打印公文', 1, 9);
