CREATE TABLE IF NOT EXISTS `doc_supervision` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `supervision_no` VARCHAR(64) NOT NULL COMMENT '督办单编号',
    `incoming_id` BIGINT NOT NULL COMMENT '收文ID',
    `handling_id` BIGINT COMMENT '处理记录ID',
    `source_doc_number` VARCHAR(128) COMMENT '来文字号（文号）',
    `doc_title` VARCHAR(256) COMMENT '公文标题',
    `supervision_type` VARCHAR(32) NOT NULL COMMENT '督办类型：timeout超时/urge_overdue催办超标',
    `responsible_user_id` VARCHAR(64) NOT NULL COMMENT '责任人ID',
    `responsible_user_name` VARCHAR(64) NOT NULL COMMENT '责任人姓名',
    `responsible_dept_id` VARCHAR(64) COMMENT '责任部门ID',
    `responsible_dept_name` VARCHAR(128) COMMENT '责任部门名称',
    `leader_id` VARCHAR(64) COMMENT '分管领导ID',
    `leader_name` VARCHAR(64) COMMENT '分管领导姓名',
    `overdue_days` INT NOT NULL DEFAULT 0 COMMENT '超时天数',
    `urge_count` INT NOT NULL DEFAULT 0 COMMENT '催办次数',
    `deadline` DATE COMMENT '办理期限',
    `supervision_content` VARCHAR(1024) COMMENT '督办内容',
    `push_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '推送状态：pending待推送/pushed已推送/failed推送失败',
    `push_time` DATETIME COMMENT '推送时间',
    `status` VARCHAR(32) NOT NULL DEFAULT 'generated' COMMENT '督办状态：generated已生成/notified已通知/processing处理中/completed已完成/closed已关闭',
    `complete_time` DATETIME COMMENT '完成时间',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_supervision_no` (`supervision_no`),
    KEY `idx_incoming_id` (`incoming_id`),
    KEY `idx_handling_id` (`handling_id`),
    KEY `idx_supervision_type` (`supervision_type`),
    KEY `idx_responsible_user_id` (`responsible_user_id`),
    KEY `idx_leader_id` (`leader_id`),
    KEY `idx_push_status` (`push_status`),
    KEY `idx_status` (`status`),
    KEY `idx_deadline` (`deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='督办单表';

CREATE TABLE IF NOT EXISTS `doc_urge_log` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `incoming_id` BIGINT NOT NULL COMMENT '收文ID',
    `handling_id` BIGINT COMMENT '处理记录ID',
    `urge_no` VARCHAR(64) NOT NULL COMMENT '催办编号',
    `urge_type` VARCHAR(32) NOT NULL COMMENT '催办方式：system系统/manual人工',
    `urged_user_id` VARCHAR(64) NOT NULL COMMENT '被催办人ID',
    `urged_user_name` VARCHAR(64) NOT NULL COMMENT '被催办人姓名',
    `urged_dept_id` VARCHAR(64) COMMENT '被催办部门ID',
    `urged_dept_name` VARCHAR(128) COMMENT '被催办部门名称',
    `urge_content` VARCHAR(1024) COMMENT '催办内容',
    `status` VARCHAR(32) NOT NULL DEFAULT 'sent' COMMENT '状态：sent已发送/acknowledged已确认',
    `acknowledge_time` DATETIME COMMENT '确认时间',
    `remark` VARCHAR(512) COMMENT '备注',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否1是',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_urge_no` (`urge_no`),
    KEY `idx_incoming_id` (`incoming_id`),
    KEY `idx_handling_id` (`handling_id`),
    KEY `idx_urged_user_id` (`urged_user_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='催办记录表';
