CREATE TABLE IF NOT EXISTS stat_efficiency (
    id BIGINT NOT NULL COMMENT '主键ID',
    stat_month VARCHAR(7) NOT NULL COMMENT '统计月份(yyyy-MM)',
    rank_type VARCHAR(10) NOT NULL COMMENT '排名类型: dept=部门 person=个人',
    target_id VARCHAR(64) NOT NULL COMMENT '目标ID(部门ID/用户ID)',
    target_name VARCHAR(128) NOT NULL COMMENT '目标名称(部门名称/用户姓名)',
    dept_id VARCHAR(64) DEFAULT NULL COMMENT '部门ID',
    dept_name VARCHAR(128) DEFAULT NULL COMMENT '部门名称',
    unit_code VARCHAR(32) DEFAULT NULL COMMENT '所属单位编码',
    unit_name VARCHAR(128) DEFAULT NULL COMMENT '所属单位名称',
    total_task BIGINT DEFAULT 0 COMMENT '任务总数',
    completed_task BIGINT DEFAULT 0 COMMENT '已办结任务数',
    overdue_task BIGINT DEFAULT 0 COMMENT '超时任务数',
    completion_rate DECIMAL(10,2) DEFAULT 0.00 COMMENT '办结率(%)',
    avg_duration_minutes BIGINT DEFAULT 0 COMMENT '平均处理时长(分钟)',
    avg_duration_text VARCHAR(64) DEFAULT NULL COMMENT '平均处理时长文本',
    efficiency_score DECIMAL(10,2) DEFAULT 0.00 COMMENT '效率得分',
    rank_no INT DEFAULT 0 COMMENT '排名',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 0=否 1=是',
    PRIMARY KEY (id),
    KEY idx_stat_month_type (stat_month, rank_type),
    KEY idx_unit (unit_code),
    KEY idx_dept (dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月度效能统计表';
