CREATE TABLE IF NOT EXISTS doc_analysis (
    id BIGINT NOT NULL COMMENT '主键ID',
    source_type VARCHAR(32) NOT NULL COMMENT '来源类型: camunda_task/camunda_instance/business_handling/business_urge',
    source_id VARCHAR(128) DEFAULT NULL COMMENT '来源记录ID',
    business_key VARCHAR(128) DEFAULT NULL COMMENT '业务主键(doc_document.id)',
    doc_number VARCHAR(64) DEFAULT NULL COMMENT '文号',
    doc_title VARCHAR(512) DEFAULT NULL COMMENT '公文标题',
    doc_type VARCHAR(32) DEFAULT NULL COMMENT '公文类型',
    process_instance_id BIGINT DEFAULT NULL COMMENT '流程实例ID',
    process_code VARCHAR(64) DEFAULT NULL COMMENT '流程编码',
    process_name VARCHAR(128) DEFAULT NULL COMMENT '流程名称',
    node_id VARCHAR(64) DEFAULT NULL COMMENT '节点ID',
    node_name VARCHAR(128) DEFAULT NULL COMMENT '节点名称',
    node_type VARCHAR(32) DEFAULT NULL COMMENT '节点类型',
    operator_id VARCHAR(64) DEFAULT NULL COMMENT '操作人ID',
    operator_name VARCHAR(128) DEFAULT NULL COMMENT '操作人姓名',
    operator_dept_id VARCHAR(64) DEFAULT NULL COMMENT '操作人部门ID',
    operator_dept_name VARCHAR(128) DEFAULT NULL COMMENT '操作人部门名称',
    operation_type VARCHAR(32) DEFAULT NULL COMMENT '操作类型: approve/reject/transfer/countersign等',
    enter_time DATETIME DEFAULT NULL COMMENT '进入时间',
    leave_time DATETIME DEFAULT NULL COMMENT '离开时间',
    duration BIGINT DEFAULT NULL COMMENT '停留时长(秒)',
    duration_text VARCHAR(64) DEFAULT NULL COMMENT '停留时长文本',
    is_overdue TINYINT DEFAULT 0 COMMENT '是否超时: 0=否 1=是',
    deadline_time DATETIME DEFAULT NULL COMMENT '截止时间',
    variables TEXT DEFAULT NULL COMMENT '流程变量(JSON)',
    extract_time DATETIME DEFAULT NULL COMMENT '抽取时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 0=否 1=是',
    PRIMARY KEY (id),
    KEY idx_source_type_id (source_type, source_id),
    KEY idx_business_key (business_key),
    KEY idx_process_instance (process_instance_id),
    KEY idx_operator (operator_id),
    KEY idx_extract_time (extract_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程数据分析表';

CREATE TABLE IF NOT EXISTS reminder_log (
    id BIGINT NOT NULL COMMENT '主键ID',
    source_type VARCHAR(32) NOT NULL COMMENT '来源类型: urge_log/supervision',
    source_id VARCHAR(128) DEFAULT NULL COMMENT '来源记录ID',
    incoming_id BIGINT DEFAULT NULL COMMENT '收文ID',
    handling_id BIGINT DEFAULT NULL COMMENT '承办ID',
    doc_number VARCHAR(64) DEFAULT NULL COMMENT '文号',
    doc_title VARCHAR(512) DEFAULT NULL COMMENT '公文标题',
    urge_no VARCHAR(64) DEFAULT NULL COMMENT '催办编号',
    urge_type VARCHAR(32) DEFAULT NULL COMMENT '催办类型: manual/system/supervision',
    urged_user_id VARCHAR(64) DEFAULT NULL COMMENT '被催办人ID',
    urged_user_name VARCHAR(128) DEFAULT NULL COMMENT '被催办人姓名',
    urged_dept_id VARCHAR(64) DEFAULT NULL COMMENT '被催办人部门ID',
    urged_dept_name VARCHAR(128) DEFAULT NULL COMMENT '被催办人部门名称',
    urge_content TEXT DEFAULT NULL COMMENT '催办内容',
    urge_status VARCHAR(32) DEFAULT NULL COMMENT '催办状态',
    acknowledge_time DATETIME DEFAULT NULL COMMENT '确认时间',
    extract_time DATETIME DEFAULT NULL COMMENT '抽取时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 0=否 1=是',
    PRIMARY KEY (id),
    KEY idx_source (source_type, source_id),
    KEY idx_incoming (incoming_id),
    KEY idx_urged_user (urged_user_id),
    KEY idx_extract_time (extract_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='催办提醒日志表';

CREATE TABLE IF NOT EXISTS reject_reason (
    id BIGINT NOT NULL COMMENT '主键ID',
    source_type VARCHAR(32) NOT NULL COMMENT '来源类型: approval_opinion',
    source_id VARCHAR(128) DEFAULT NULL COMMENT '来源记录ID',
    business_key VARCHAR(128) DEFAULT NULL COMMENT '业务主键',
    doc_number VARCHAR(64) DEFAULT NULL COMMENT '文号',
    doc_title VARCHAR(512) DEFAULT NULL COMMENT '公文标题',
    process_instance_id BIGINT DEFAULT NULL COMMENT '流程实例ID',
    task_id BIGINT DEFAULT NULL COMMENT '任务ID',
    node_id VARCHAR(64) DEFAULT NULL COMMENT '退回节点ID',
    node_name VARCHAR(128) DEFAULT NULL COMMENT '退回节点名称',
    approval_type VARCHAR(32) DEFAULT NULL COMMENT '审批类型: reject/return',
    reject_reason TEXT DEFAULT NULL COMMENT '退回原因',
    approver_id VARCHAR(64) DEFAULT NULL COMMENT '退回操作人ID',
    approver_name VARCHAR(128) DEFAULT NULL COMMENT '退回操作人姓名',
    approver_dept_id VARCHAR(64) DEFAULT NULL COMMENT '退回操作人部门ID',
    approver_dept_name VARCHAR(128) DEFAULT NULL COMMENT '退回操作人部门名称',
    target_node_id VARCHAR(64) DEFAULT NULL COMMENT '退回目标节点ID',
    target_node_name VARCHAR(128) DEFAULT NULL COMMENT '退回目标节点名称',
    target_user_id VARCHAR(64) DEFAULT NULL COMMENT '退回目标用户ID',
    target_user_name VARCHAR(128) DEFAULT NULL COMMENT '退回目标用户名称',
    approval_time DATETIME DEFAULT NULL COMMENT '退回时间',
    extract_time DATETIME DEFAULT NULL COMMENT '抽取时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除 0=否 1=是',
    PRIMARY KEY (id),
    KEY idx_source (source_type, source_id),
    KEY idx_business_key (business_key),
    KEY idx_approval_type (approval_type),
    KEY idx_approver (approver_id),
    KEY idx_extract_time (extract_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退回原因分析表';
